# Generated by Django 4.1.3 on 2022-12-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ceated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='modiefied_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
