# Generated by Django 4.1.3 on 2022-12-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_document_ceated_at_document_modiefied_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='modiefied_at',
            new_name='modified_at',
        ),
    ]
